### PR TITLE
User update page does not gain width with error message

### LINKED ISSUE #136: Background width of the update user form, in user-profile page, is changing when an error is shown. Needs to be a fixed width

### PR DESCRIPTION
**Pull request by ghost**
Fixed the update page increasing in width if error message is larger than the width of the box

### CODE REVIEW

**Comment by ghost** [comment]
#136

**Review by Daebaks — APPROVED** [review]

**Review by willmoore1 — CHANGES_REQUESTED** [review]
no magic number

**Review by jw5374 — COMMENTED** [review]
THIS DOES NOT MATTER, PLEASE DON'T PUT PX AMOUNTS

**Comment by Daebaks** [comment]
Not sure about this.

**Review by Daebaks — CHANGES_REQUESTED** [review]
"max-width: 270px;"

**Comment by ghost** [comment]
So just close the pull request then?

**Comment by jw5374** [comment]
just close it yea

**Pull request closed without merging**
